name: Docker Image CI

on:
  push:
    branches: [actions-testing]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GHCR_REPO: "ghcr.io/nfb/clair-db"
      POSTGRES_IMAGE: "postgres:11.6-alpine"
      CLAIR_VERSION: "v2.1.8"
      CLAIR_LOCAL_SCAN_IMAGE: "arminc/clair-local-scan"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          install: true

      - name: Start Postgres and run clair
        run: |
          docker pull $POSTGRES_IMAGE
          docker run -d --name postgres -e 'PGDATA=/var/lib/postgresql/clair' -e POSTGRES_PASSWORD=password $POSTGRES_IMAGE
      - name: Wait for database
        run: |
          sleep 30
      - name: Docker Postgres info
        run: |
          docker ps -a
          docker logs postgres
      - name: Run Clair
        run: |
          docker run --rm -d --link postgres:postgres -e PGPASSWORD=password $POSTGRES_IMAGE pg_isready -U postgres -h postgres
          docker run -d --name clair --link postgres:postgres $CLAIR_LOCAL_SCAN_IMAGE
      - name: Wait for clair
        run: |
          sleep 10
      - name: Docker Postgres info
        run: |
          docker ps -a
          docker logs postgres
      - name: Docker Clair info
        run: |
          docker ps -a
          docker logs clair
      - name: Checking
        run: |
          ./check.sh
      - name: Docker logs
        run: |
          docker logs clair
      - name: Tag images
        run: |
          docker stop clair
          docker stop postgres
          docker commit postgres :$(date +%Y-%m-%d)
          docker tag $GHCR_REPO:$(date +%Y-%m-%d) $GHCR_REPO:latest
          docker tag $CLAIR_LOCAL_SCAN_IMAGE ${CLAIR_LOCAL_SCAN_IMAGE}:${CLAIR_VERSION}_${GITHUB_SHA}
          docker images
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT  }}
      - name: Push images
        run: |
          docker push $GHCR_REPO:$(date +%Y-%m-%d)
          docker push $GHCR_REPO:latest
